name: calculator_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  math_expressions: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # assets
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/

  #-FONTS
  fonts:
    - family: AlbertSans
      fonts:
        - asset: assets/fonts/AlbertSans/AlbertSans-Regular.ttf
        - asset: assets/fonts/AlbertSans/AlbertSans-Light.ttf
          weight: 100
        - asset: assets/fonts/AlbertSans/AlbertSans-Medium.ttf
          weight: 200
        - asset: assets/fonts/AlbertSans/AlbertSans-MediumItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/AlbertSans/AlbertSans-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/AlbertSans/AlbertSans-SemiBoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/AlbertSans/AlbertSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/AlbertSans/AlbertSans-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/AlbertSans/AlbertSans-Italic.ttf
          style: italic
